// AUTHS
export const AUTH_CREATE_AVATAR = "AUTH/CREATE_AVATAR";
export const AUTH_DELETE_AVATAR = "AUTH/DELETE_AVATAR";
export const AUTH_SET_PROFILE = "AUTH/SET_PROFILE";
export const AUTH_SIGNIN = "AUTH/SIGNIN";
export const AUTH_SIGNIN_ATTEMPT = "AUTH/SIGNIN_ATTEMPT";
export const AUTH_SIGNIN_ON_LOAD = "AUTH/SIGNIN_ON_LOAD";
export const AUTH_SIGNIN_SESSION = "AUTH/SIGNIN_SESSION";
export const AUTH_SIGNOUT = "AUTH/SIGNOUT";
export const AUTH_SIGNOUT_SESSION = "AUTH/SIGNOUT_SESSION";
export const AUTH_SIGNUP = "AUTH/SIGNUP";
export const AUTH_UPDATE_AVATAR = "AUTH/UPDATE_AVATAR";
export const AUTH_UPDATE_PROFILE = "AUTH/UPDATE_PROFILE";

// MESSAGES
export const RESET_MESSAGES = "RESET_MESSAGES";
export const SET_ERROR = "SET_ERROR";
export const SET_MESSAGE = "SET_MESSAGE";
