// AUTHS
export const AUTH_CREATE_AVATAR = "AUTH/CREATE_AVATAR";
export const AUTH_DELETE_AVATAR = "AUTH/DELETE_AVATAR";
export const AUTH_SET_PROFILE = "AUTH/SET_PROFILE";
export const AUTH_SIGNIN = "AUTH/SIGNIN";
export const AUTH_SIGNIN_ATTEMPT = "AUTH/SIGNIN_ATTEMPT";
export const AUTH_SIGNIN_SESSION = "AUTH/SIGNIN_SESSION";
export const AUTH_SIGNOUT = "AUTH/SIGNOUT";
export const AUTH_SIGNOUT_SESSION = "AUTH/SIGNOUT_SESSION";
export const AUTH_SIGNUP = "AUTH/SIGNUP";
export const AUTH_UPDATE_AVATAR = "AUTH/UPDATE_AVATAR";
export const AUTH_UPDATE_PROFILE = "AUTH/UPDATE_PROFILE";

// QUESTIONS
export const QUESTIONS_CREATE = "QUESTIONS/CREATE";
export const QUESTIONS_CREATE_COMMENT = "QUESTIONS/CREATE_COMMENT";
export const QUESTIONS_FETCH = "QUESTIONS/FETCH";
export const QUESTIONS_FETCH_ONE = "QUESTIONS/FETCH_ONE";
export const QUESTIONS_SET = "QUESTIONS/SET";
export const QUESTIONS_SET_ONE = "QUESTIONS/SET_ONE";

// MESSAGES
export const RESET_MESSAGES = "RESET_MESSAGES";
export const SET_ERROR = "SET_ERROR";
export const SET_MESSAGE = "SET_MESSAGE";
