export default [
  {
    name: "title",
    type: "text",
    label: "Title",
    placeholder: "Enter a question title...",
    value: "",
    errors: "",
    required: true,
  },
  {
    name: "tag",
    type: "tag",
    label: "Tags",
    placeholder: "Search for related tags...",
    tooltip: "Selecting tags will make the question more specific!",
    value: [],
    errors: "",
    options: [],
    required: false,
  },
  {
    name: "question",
    type: "editor",
    label: "Question",
    value: "",
    errors: "",
    required: true,
  },
],